In [1]:
from google.colab import files
uploaded = files.upload()

Saving hotel_bookings.csv to hotel_bookings.csv

In [2]:
# Importing libraries
import pandas as pd

# Reading in dataset
hotels_df = pd.read_csv('hotel_bookings.csv')
hotels_df.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.0,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22

**Data Cleaning**

In [3]:
# Exploring the columns 
hotels_df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [4]:
hotels_df['country'].describe()

count     118902
unique       177
top          PRT
freq       48590
Name: country, dtype: object

In [5]:
# Finding null values
for column in hotels_df.columns:
    print(f"Column {column} has {hotels_df[column].isnull().sum()} null values.")

Column hotel has 0 null values.
Column is_canceled has 0 null values.
Column lead_time has 0 null values.
Column arrival_date_year has 0 null values.
Column arrival_date_month has 0 null values.
Column arrival_date_week_number has 0 null values.
Column arrival_date_day_of_month has 0 null values.
Column stays_in_weekend_nights has 0 null values.
Column stays_in_week_nights has 0 null values.
Column adults has 0 null values.
Column children has 4 null values.
Column babies has 0 null values.
Column meal has 0 null values.
Column country has 488 null values.
Column market_segment has 0 null values.
Column distribution_channel has 0 null values.
Column is_repeated_guest has 0 null values.
Column previous_cancellations has 0 null values.
Column previous_bookings_not_canceled has 0 null values.
Column reserved_room_type has 0 null values.
Column assigned_room_type has 0 null values.
Column booking_changes has 0 null values.
Column deposit_type has 0 null values.
Column agent has 16340 null values.
Column company has 112593 null values.
Column days_in_waiting_list has 0 null values.
Column customer_type has 0 null values.
Column adr has 0 null values.
Column required_car_parking_spaces has 0 null values.
Column total_of_special_requests has 0 null values.
Column reservation_status has 0 null values.
Column reservation_status_date has 0 null values.

In [6]:
# Finding duplicate values (Should I delete these entries, no unique identifier per booking so are they truly duplicates or..)
print(f"Duplicate entries: {hotels_df.duplicated().sum()}")

Duplicate entries: 31994

In [7]:
# Copy of original df first
hotels_df_2 = hotels_df.copy()

# Dropping the 'agent' and 'company' columns 
hotels_df_2.drop(columns = ['agent', 'company'], inplace=True)
hotels_df_2.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [9]:
# Dropping the 4 ROWS with missing 'children' data
# Dropping the 488 ROWS with missing 'country' data
hotels_df_2 = hotels_df_2.dropna()

# Rechecking NaN values 
for column in hotels_df_2.columns:
    print(f"Column {column} has {hotels_df_2[column].isnull().sum()} null values.")

Column hotel has 0 null values.
Column is_canceled has 0 null values.
Column lead_time has 0 null values.
Column arrival_date_year has 0 null values.
Column arrival_date_month has 0 null values.
Column arrival_date_week_number has 0 null values.
Column arrival_date_day_of_month has 0 null values.
Column stays_in_weekend_nights has 0 null values.
Column stays_in_week_nights has 0 null values.
Column adults has 0 null values.
Column children has 0 null values.
Column babies has 0 null values.
Column meal has 0 null values.
Column country has 0 null values.
Column market_segment has 0 null values.
Column distribution_channel has 0 null values.
Column is_repeated_guest has 0 null values.
Column previous_cancellations has 0 null values.
Column previous_bookings_not_canceled has 0 null values.
Column reserved_room_type has 0 null values.
Column assigned_room_type has 0 null values.
Column booking_changes has 0 null values.
Column deposit_type has 0 null values.
Column days_in_waiting_list has 0 null values.
Column customer_type has 0 null values.
Column adr has 0 null values.
Column required_car_parking_spaces has 0 null values.
Column total_of_special_requests has 0 null values.
Column reservation_status has 0 null values.
Column reservation_status_date has 0 null values.

In [10]:
# Dropping more columns that may not be necessary for our analysis 
# Drop "reservation_status_date", "reserved_room_type", "assigned_room_type", "arrival_date_week_number", "distribution_channel"
hotels_df_2.drop(columns = ["reservation_status_date", "reserved_room_type", "assigned_room_type", "arrival_date_week_number", "distribution_channel"], inplace=True)
hotels_df_2.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_day_of_month',
       'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children',
       'babies', 'meal', 'country', 'market_segment', 'is_repeated_guest',
       'previous_cancellations', 'previous_bookings_not_canceled',
       'booking_changes', 'deposit_type', 'days_in_waiting_list',
       'customer_type', 'adr', 'required_car_parking_spaces',
       'total_of_special_requests', 'reservation_status'],
      dtype='object')

In [11]:
# Export clean dataset
# upload to database? 
hotels_df_2.to_csv('clean_hotel_df.csv', encoding='utf-8-sig', index=False)  
files.download('clean_hotel_df.csv')

**Data Preprocessing for Machine Learning Model**

In [12]:
# Importing libraries
from google.colab import files
uploaded = files.upload()
import pandas as pd

# Import our input dataset
df_2 = pd.read_csv('clean_hotel_df.csv')
df_2.head(10)

Saving clean_hotel_df.csv to clean_hotel_df (1).csv

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,previous_cancellations,previous_bookings_not_canceled,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status
0,Resort Hotel,0,342,2015,July,1,0,0,2,0.0,...,0,0,3,No Deposit,0,Transient,0.0,0,0,Check-Out
1,Resort Hotel,0,737,2015,July,1,0,0,2,0.0,...,0,0,4,No Deposit,0,Transient,0.0,0,0,Check-Out
2,Resort Hotel,0,7,2015,July,1,0,1,1,0.0,...,0,0,0,No Deposit,0,Transient,75.0,0,0,Check-Out
3,Resort Hotel,0,13,2015,July,1,0,1,1,0.0,...,0,0,0,No Deposit,0,Transient,75.0,0,0,Check-Out
4,Resort Hotel,0,14,2015,July,1,0,2,2,0.0,...,0,0,0,No Deposit,0,Transient,98.0,0,1,Check-Out
5,Resort Hotel,0,14,2015,July,1,0,2,2,0.0,...,0,0,0,No Deposit,0,Transient,98.0,0,1,Check-Out
6,Resort Hotel,0,0,2015,July,1,0,2,2,0.0,...,0,0,0,No Deposit,0,Transient,107.0,0,0,Check-Out
7,Resort Hotel,0,9,2015,July,1,0,2,2,0.0,...,0,0,0,No Deposit,0,Transient,103.0,0,1,Check-Out
8,Resort Hotel,1,85,2015,July,1,0,3,2,0.0,...,0,0,0,No Deposit,0,Transient,82.0,0,1,Canceled
9,Resort Hotel,1,75,2015,July,1,0,3,2,0.0,...,0,0,0,No Deposit,0,Transient,105.5,0,0,Canceled

In [13]:
# Drop more columns 
df_2.drop(columns = ["reservation_status", "arrival_date_year", "arrival_date_day_of_month", "booking_changes", "country"], inplace=True)
df_2.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_month',
       'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children',
       'babies', 'meal', 'market_segment', 'is_repeated_guest',
       'previous_cancellations', 'previous_bookings_not_canceled',
       'deposit_type', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests'],
      dtype='object')

In [14]:
# Making a copy of the df
df_enc = df_2.copy()

In [15]:
# Encoding month column values
months_num = {
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12,
}


df_enc['arrival_date_month'] = df_enc['arrival_date_month'].apply(lambda x : months_num[x])
df_enc.head()

,hotel,is_canceled,lead_time,arrival_date_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,market_segment,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
0,Resort Hotel,0,342,7,0,0,2,0.0,0,BB,Direct,0,0,0,No Deposit,0,Transient,0.0,0,0
1,Resort Hotel,0,737,7,0,0,2,0.0,0,BB,Direct,0,0,0,No Deposit,0,Transient,0.0,0,0
2,Resort Hotel,0,7,7,0,1,1,0.0,0,BB,Direct,0,0,0,No Deposit,0,Transient,75.0,0,0
3,Resort Hotel,0,13,7,0,1,1,0.0,0,BB,Corporate,0,0,0,No Deposit,0,Transient,75.0,0,0
4,Resort Hotel,0,14,7,0,2,2,0.0,0,BB,Online TA,0,0,0,No Deposit,0,Transient,98.0,0,1

In [16]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [17]:
hotel_cat = df_enc.dtypes[df_enc.dtypes == 'object'].index.tolist()

df_enc[hotel_cat].nunique()

hotel             2
meal              5
market_segment    7
deposit_type      3
customer_type     4
dtype: int64

In [18]:
# Create OneHotEncoder instance 
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(df_enc[hotel_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(hotel_cat)
encode_df.head()

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,hotel_City Hotel,hotel_Resort Hotel,meal_BB,meal_FB,meal_HB,meal_SC,meal_Undefined,market_segment_Aviation,market_segment_Complementary,market_segment_Corporate,...,market_segment_Groups,market_segment_Offline TA/TO,market_segment_Online TA,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [19]:
# Merge one-hot encoded features and drop the originals
df_enc = df_enc.merge(encode_df,left_index=True, right_index=True)
df_enc = df_enc.drop(hotel_cat,1)
df_enc.head()

<ipython-input-19-f5f5e4169faf>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df_enc = df_enc.drop(hotel_cat,1)

,is_canceled,lead_time,arrival_date_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,...,market_segment_Groups,market_segment_Offline TA/TO,market_segment_Online TA,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,0,342,7,0,0,2,0.0,0,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0,737,7,0,0,2,0.0,0,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0,7,7,0,1,1,0.0,0,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0,13,7,0,1,1,0.0,0,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0,14,7,0,2,2,0.0,0,0,0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [20]:
# Split our preprocessed data into our features and target arrays
y = df_enc["is_canceled"].values
X = df_enc.drop(["is_canceled"],1).values

from sklearn.model_selection import train_test_split
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

<ipython-input-20-1e18015104da>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = df_enc.drop(["is_canceled"],1).values

In [21]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

**Model Building: Logistic Regression**

In [22]:
# Create our logistic regression model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs', max_iter=100, random_state=1)
classifier

LogisticRegression(random_state=1)

In [23]:
# Training the model
classifier.fit(X_train_scaled, y_train)

LogisticRegression(random_state=1)

In [24]:
# Create predictions
y_pred = classifier.predict(X_test_scaled)
pd.DataFrame({"Prediction": y_pred, "Actual": y_test})

       Prediction  Actual
0               0       0
1               0       0
2               0       0
3               0       0
4               1       1
...           ...     ...
29720           0       1
29721           0       0
29722           1       1
29723           0       1
29724           0       0

[29725 rows x 2 columns]

In [25]:
# Validate the model's performance
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.807771236333053

In [26]:
# Validating the model using the test data
print(f"Training Data Score: {classifier.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test_scaled, y_test)}")

Training Data Score: 0.8091014096195036
Testing Data Score: 0.807771236333053

In [27]:
# Confusion Matrix 
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[17497  1196]
 [ 4518  6514]]

In [28]:
# Classification Report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.79      0.94      0.86     18693
           1       0.84      0.59      0.70     11032

    accuracy                           0.81     29725
   macro avg       0.82      0.76      0.78     29725
weighted avg       0.81      0.81      0.80     29725

**Model Building: Random Forrest Classifier**

In [29]:
from sklearn.ensemble import RandomForestClassifier

In [30]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

In [31]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [32]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [33]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0        17203         1490
Actual 1         2763         8269

In [34]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
acc_score

0.8569217830109336

In [35]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0        17203         1490
Actual 1         2763         8269

Accuracy Score : 0.8569217830109336
Classification Report
              precision    recall  f1-score   support

           0       0.86      0.92      0.89     18693
           1       0.85      0.75      0.80     11032

    accuracy                           0.86     29725
   macro avg       0.85      0.83      0.84     29725
weighted avg       0.86      0.86      0.85     29725

## Testing Gradient Boosting Classifier to improve our recall percentage

Choosing best learning rate

In [78]:
from sklearn.ensemble import GradientBoostingClassifier

# Create a classifier object
learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1]
for learning_rate in learning_rates:
    classifier = GradientBoostingClassifier(n_estimators=300,
                                            learning_rate=learning_rate,
                                            max_features=10,
                                            max_depth=8,
                                            random_state=0)

    # Fit the model
    classifier.fit(X_train_scaled, y_train)
    print("Learning rate: ", learning_rate)

    # Score the model
    print("Accuracy score (training): {0:.3f}".format(
        classifier.score(
            X_train_scaled,
            y_train)))
    print("Accuracy score (validation): {0:.3f}".format(
        classifier.score(
            X_test_scaled,
            y_test)))
    print()

Learning rate:  0.05
Accuracy score (training): 0.856
Accuracy score (validation): 0.838

Learning rate:  0.1
Accuracy score (training): 0.881
Accuracy score (validation): 0.845

Learning rate:  0.25
Accuracy score (training): 0.932
Accuracy score (validation): 0.850

Learning rate:  0.5
Accuracy score (training): 0.966
Accuracy score (validation): 0.847

Learning rate:  0.75
Accuracy score (training): 0.944
Accuracy score (validation): 0.833

Learning rate:  1
Accuracy score (training): 0.908
Accuracy score (validation): 0.806

Choose Learning rate

In [79]:
# Choose a learning rate and create classifier
# In our case the learning rate with the highest accuracy score after validation is 1
classifier = GradientBoostingClassifier(n_estimators=300,
                                        learning_rate=0.25,
                                        max_features=10,
                                        max_depth=8,
                                        random_state=0)

# Fit the model
classifier.fit(X_train_scaled, y_train)

# Make Prediction
predictions = classifier.predict(X_test_scaled)
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).head(10)

   Prediction  Actual
0           0       0
1           0       0
2           0       0
3           0       0
4           1       1
5           0       0
6           0       0
7           0       0
8           0       0
9           0       0

Evaluate the model

In [80]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
acc_score = accuracy_score(y_test, predictions)
print(f"Accuracy Score : {acc_score}")

Accuracy Score : 0.8495542472666106

In [81]:
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
   cm, index=["Actual 0", "Actual 1"],
   columns=["Predicted 0", "Predicted 1"]
)
display(cm_df)

          Predicted 0  Predicted 1
Actual 0        17083         1610
Actual 1         2862         8170

In [82]:
print("Classification Report")
print(classification_report(y_test, predictions))

Classification Report
              precision    recall  f1-score   support

           0       0.86      0.91      0.88     18693
           1       0.84      0.74      0.79     11032

    accuracy                           0.85     29725
   macro avg       0.85      0.83      0.83     29725
weighted avg       0.85      0.85      0.85     29725