In [4]:
from google.colab import files 
uploaded = files.upload()

Saving hotel_bookings.csv to hotel_bookings.csv

In [2]:
import pandas as pd
import seaborn as sea
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib.pyplot as plt

# Imports for Machine Learning 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import tensorflow as tf

In [5]:
hotels_df = pd.read_csv('hotel_bookings.csv')
hotels_df.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.0,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22

In [7]:
hotels_df.shape

(119390, 32)

In [8]:
# Checking datatypes of columns
hotels_df.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
dtype: object

In [10]:
# Create Correlation matrix
hotels_df.corr()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
is_canceled,1.000000,0.293123,0.016660,0.008148,-0.006130,-0.001791,0.024765,0.060017,0.005048,-0.032491,-0.084793,0.110133,-0.057358,-0.144381,-0.083114,-0.020642,0.054186,0.047557,-0.195498,-0.234658
lead_time,0.293123,1.000000,0.040142,0.126871,0.002268,0.085671,0.165799,0.119519,-0.037622,-0.020915,-0.124410,0.086042,-0.073548,0.000149,-0.069741,0.151464,0.170084,-0.063077,-0.116451,-0.095712
arrival_date_year,0.016660,0.040142,1.000000,-0.540561,-0.000221,0.021497,0.030883,0.029635,0.054624,-0.013192,0.010341,-0.119822,0.029218,0.030872,0.063457,0.259095,-0.056497,0.197580,-0.013684,0.108531
arrival_date_week_number,0.008148,0.126871,-0.540561,1.000000,0.066809,0.018208,0.015558,0.025909,0.005518,0.010395,-0.030131,0.035501,-0.020904,0.005508,-0.031201,-0.076760,0.022933,0.075791,0.001920,0.026149
arrival_date_day_of_month,-0.006130,0.002268,-0.000221,0.066809,1.000000,-0.016354,-0.028174,-0.001566,0.014544,-0.000230,-0.006145,-0.027011,-0.000300,0.010613,0.001487,0.044858,0.022728,0.030245,0.008683,0.003062
stays_in_weekend_nights,-0.001791,0.085671,0.021497,0.018208,-0.016354,1.000000,0.498969,0.091871,0.045793,0.018483,-0.087239,-0.012775,-0.042715,0.063281,0.140739,0.066749,-0.054151,0.049342,-0.018554,0.072671
stays_in_week_nights,0.024765,0.165799,0.030883,0.015558,-0.028174,0.498969,1.000000,0.092976,0.044203,0.020191,-0.097245,-0.013992,-0.048743,0.096209,0.182382,0.182211,-0.002020,0.065237,-0.024859,0.068192
adults,0.060017,0.119519,0.029635,0.025909,-0.001566,0.091871,0.092976,1.000000,0.030447,0.018146,-0.146426,-0.006738,-0.107983,-0.051673,-0.035594,0.207793,-0.008283,0.230641,0.014785,0.122884
children,0.005048,-0.037622,0.054624,0.005518,0.014544,0.045793,0.044203,0.030447,1.000000,0.024030,-0.032859,-0.024730,-0.021072,0.048949,0.041066,0.030931,-0.033273,0.324854,0.056253,0.081745
babies,-0.032491,-0.020915,-0.013192,0.010395,-0.000230,0.018483,0.020191,0.018146,0.024030,1.000000,-0.008943,-0.007501,-0.006550,0.083440,0.036184,0.019206,-0.010621,0.029186,0.037383,0.097889
is_repeated_guest,-0.084793,-0.124410,0.010341,-0.030131,-0.006145,-0.087239,-0.097245,-0.146426,-0.032859,-0.008943,1.000000,0.082293,0.418056,0.012092,0.031527,-0.244586,-0.022235,-0.134314,0.077090,0.013050
previous_cancellations,0.110133,0.086042,-0.119822,0.035501,-0.027011,-0.012775,-0.013992,-0.006738,-0.024730,-0.007501,0.082293,1.000000,0.152728,-0.026993,-0.012488,-0.184574,0.005929,-0.065646,-0.018492,-0.048384
previous_bookings_not_canceled,-0.057358,-0.073548,0.029218,-0.020904,-0.000300,-0.042715,-0.048743,-0.107983,-0.021072,-0.006550,0.418056,0.152728,1.000000,0.011608,0.023252,-0.208557,-0.009397,-0.072144,0.047653,0.037824
booking_changes,-0.144381,0.000149,0.030872,0.005508,0.010613,0.063281,0.096209,-0.051673,0.048949,0.083440,0.012092,-0.026993,0.011608,1.000000,0.067010,0.122098,-0.011634,0.019618,0.065620,0.052833
agent,-0.083114,-0.069741,0.063457,-0.031201,0.001487,0.140739,0.182382,-0.035594,0.041066,0.036184,0.031527,-0.012488,0.023252,0.067010,1.000000,0.350746,-0.055151,-0.024695,0.177353,0.034162
company,-0.020642,0.151464,0.259095,-0.076760,0.044858,0.066749,0.182211,0.207793,0.030931,0.019206,-0.244586,-0.184574,-0.208557,0.122098,0.350746,1.000000,0.000411,0.086376,-0.012916,-0.098558
days_in_waiting_list,0.054186,0.170084,-0.056497,0.022933,0.022728,-0.054151,-0.002020,-0.008283,-0.033273,-0.010621,-0.022235,0.005929,-0.009397,-0.011634,-0.055151,0.000411,1.000000,-0.040756,-0.030600,-0.082730
adr,0.047557,-0.063077,0.197580,0.075791,0.030245,0.049342,0.065237,0.230641,0.324854,0.029186,-0.134314,-0.065646,-0.072144,0.019618,-0.024695,0.086376,-0.040756,1.000000,0.056628,0.172185
required_car_parking_spaces,-0.195498,-0.116451,-0.013684,0.001920,0.008683,-0.018554,-0.024859,0.014785,0.056253,0.037383,0.077090,-0.018492,0.047653,0.065620,0.177353,-0.012916,-0.030600,0.056628,1.000000,0.082626
total_of_special_requests,-0.234658,-0.095712,0.108531,0.026149,0.003062,0.072671,0.068192,0.122884,0.081745,0.097889,0.013050,-0.048384,0.037824,0.052833,0.034162,-0.098558,-0.082730,0.172185,0.082626,1.000000

In [11]:
# Checking for null or missing values
hotels_df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [12]:
# Copy original data frame into a new one to clean and drop columns/rows with a large amount of null values
hotel2_df = hotels_df.copy()
hotel2_df.drop(columns=['agent','company'],inplace=True)
hotel2_df.isnull().sum()

hotel                               0
is_canceled                         0
lead_time                           0
arrival_date_year                   0
arrival_date_month                  0
arrival_date_week_number            0
arrival_date_day_of_month           0
stays_in_weekend_nights             0
stays_in_week_nights                0
adults                              0
children                            4
babies                              0
meal                                0
country                           488
market_segment                      0
distribution_channel                0
is_repeated_guest                   0
previous_cancellations              0
previous_bookings_not_canceled      0
reserved_room_type                  0
assigned_room_type                  0
booking_changes                     0
deposit_type                        0
days_in_waiting_list                0
customer_type                       0
adr                                 0
required_car_parking_spaces         0
total_of_special_requests           0
reservation_status                  0
reservation_status_date             0
dtype: int64

In [13]:
# Dropping null values in columns 'children' and 'country'
hotel2_df = hotel2_df.dropna()
hotel2_df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

In [15]:
hotel2_df.to_csv('hotel_2_data.csv',index=False)

In [16]:
clean_hotel_df = hotel2_df.copy()
clean_hotel_df.drop(columns = ['reservation_status_date','reserved_room_type','assigned_room_type',
                           'arrival_date_week_number','distribution_channel','country'],inplace = True)
clean_hotel_df.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,previous_cancellations,previous_bookings_not_canceled,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status
0,Resort Hotel,0,342,2015,July,1,0,0,2,0.0,...,0,0,3,No Deposit,0,Transient,0.0,0,0,Check-Out
1,Resort Hotel,0,737,2015,July,1,0,0,2,0.0,...,0,0,4,No Deposit,0,Transient,0.0,0,0,Check-Out
2,Resort Hotel,0,7,2015,July,1,0,1,1,0.0,...,0,0,0,No Deposit,0,Transient,75.0,0,0,Check-Out
3,Resort Hotel,0,13,2015,July,1,0,1,1,0.0,...,0,0,0,No Deposit,0,Transient,75.0,0,0,Check-Out
4,Resort Hotel,0,14,2015,July,1,0,2,2,0.0,...,0,0,0,No Deposit,0,Transient,98.0,0,1,Check-Out
5,Resort Hotel,0,14,2015,July,1,0,2,2,0.0,...,0,0,0,No Deposit,0,Transient,98.0,0,1,Check-Out
6,Resort Hotel,0,0,2015,July,1,0,2,2,0.0,...,0,0,0,No Deposit,0,Transient,107.0,0,0,Check-Out
7,Resort Hotel,0,9,2015,July,1,0,2,2,0.0,...,0,0,0,No Deposit,0,Transient,103.0,0,1,Check-Out
8,Resort Hotel,1,85,2015,July,1,0,3,2,0.0,...,0,0,0,No Deposit,0,Transient,82.0,0,1,Canceled
9,Resort Hotel,1,75,2015,July,1,0,3,2,0.0,...,0,0,0,No Deposit,0,Transient,105.5,0,0,Canceled

In [18]:
clean_hotel_df.to_csv('clean_hotel_df.csv',index = False)

In [19]:
clean_hotel_df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_day_of_month',
       'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children',
       'babies', 'meal', 'market_segment', 'is_repeated_guest',
       'previous_cancellations', 'previous_bookings_not_canceled',
       'booking_changes', 'deposit_type', 'days_in_waiting_list',
       'customer_type', 'adr', 'required_car_parking_spaces',
       'total_of_special_requests', 'reservation_status'],
      dtype='object')

In [20]:
# Making a copy of the df
df_enc = clean_hotel_df.copy()

In [21]:
# Encoding month column values
months_num = {
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12,
}


df_enc['arrival_date_month'] = df_enc['arrival_date_month'].apply(lambda x : months_num[x])
df_enc.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,previous_cancellations,previous_bookings_not_canceled,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status
0,Resort Hotel,0,342,2015,7,1,0,0,2,0.0,...,0,0,3,No Deposit,0,Transient,0.0,0,0,Check-Out
1,Resort Hotel,0,737,2015,7,1,0,0,2,0.0,...,0,0,4,No Deposit,0,Transient,0.0,0,0,Check-Out
2,Resort Hotel,0,7,2015,7,1,0,1,1,0.0,...,0,0,0,No Deposit,0,Transient,75.0,0,0,Check-Out
3,Resort Hotel,0,13,2015,7,1,0,1,1,0.0,...,0,0,0,No Deposit,0,Transient,75.0,0,0,Check-Out
4,Resort Hotel,0,14,2015,7,1,0,2,2,0.0,...,0,0,0,No Deposit,0,Transient,98.0,0,1,Check-Out

In [22]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [23]:
hotel_cat = df_enc.dtypes[df_enc.dtypes == 'object'].index.tolist()

df_enc[hotel_cat].nunique()

hotel                 2
meal                  5
market_segment        7
deposit_type          3
customer_type         4
reservation_status    3
dtype: int64

In [24]:
# Create OneHotEncoder instance 
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(df_enc[hotel_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(hotel_cat)
encode_df.head()

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,hotel_City Hotel,hotel_Resort Hotel,meal_BB,meal_FB,meal_HB,meal_SC,meal_Undefined,market_segment_Aviation,market_segment_Complementary,market_segment_Corporate,...,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,reservation_status_Canceled,reservation_status_Check-Out,reservation_status_No-Show
0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [25]:
# Merge one-hot encoded features and drop the originals
df_enc = df_enc.merge(encode_df,left_index=True, right_index=True)
df_enc = df_enc.drop(hotel_cat,1)
df_enc.head()

<ipython-input-25-f5f5e4169faf>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df_enc = df_enc.drop(hotel_cat,1)

,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,reservation_status_Canceled,reservation_status_Check-Out,reservation_status_No-Show
0,0,342,2015,7,1,0,0,2,0.0,0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0,737,2015,7,1,0,0,2,0.0,0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0,7,2015,7,1,0,1,1,0.0,0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,0,13,2015,7,1,0,1,1,0.0,0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,0,14,2015,7,1,0,2,2,0.0,0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [27]:
# Split our preprocessed data into our features and target arrays
y = df_enc["is_canceled"].values
X = df_enc.drop(["is_canceled"],1).values

from sklearn.model_selection import train_test_split
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

<ipython-input-27-1e18015104da>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = df_enc.drop(["is_canceled"],1).values

In [28]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

Model Building: Logistic Regression

In [29]:
# Create our logistic regression model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs', max_iter=100, random_state=1)
classifier

LogisticRegression(random_state=1)

In [30]:
# Training the model
classifier.fit(X_train_scaled, y_train)

LogisticRegression(random_state=1)

In [31]:
# Create predictions
y_pred = classifier.predict(X_test_scaled)
pd.DataFrame({"Prediction": y_pred, "Actual": y_test})

       Prediction  Actual
0               0       0
1               0       0
2               1       1
3               0       0
4               0       0
...           ...     ...
29597           1       1
29598           0       0
29599           0       0
29600           0       0
29601           1       1

[29602 rows x 2 columns]

In [32]:
# Validate the model's performance
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.9199716235389501

In [33]:
# Validating the model using the test data
print(f"Training Data Score: {classifier.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test_scaled, y_test)}")

Training Data Score: 0.9172334579523445
Testing Data Score: 0.9199716235389501

In [34]:
# Confusion Matrix 
from sklearn.metrics import confusion_matrix, classification_report
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[17191  1286]
 [ 1083 10042]]

In [35]:
# Classification Report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.94      0.93      0.94     18477
           1       0.89      0.90      0.89     11125

    accuracy                           0.92     29602
   macro avg       0.91      0.92      0.92     29602
weighted avg       0.92      0.92      0.92     29602

Model Building: Random Forrest Classifier

In [37]:

from sklearn.ensemble import RandomForestClassifier

In [38]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=1)

In [39]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [40]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [41]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0        18105          372
Actual 1          826        10299

In [42]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
acc_score

0.9595297615026012

In [43]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0        18105          372
Actual 1          826        10299

Accuracy Score : 0.9595297615026012
Classification Report
              precision    recall  f1-score   support

           0       0.96      0.98      0.97     18477
           1       0.97      0.93      0.95     11125

    accuracy                           0.96     29602
   macro avg       0.96      0.95      0.96     29602
weighted avg       0.96      0.96      0.96     29602